task: pointButton

# ==== Model parameters ====
hidden1: 512
hidden2: 512
num_layers: 3
dropout: 0.2
v_lr: 0.0002 #2e-4
cost_v_lr: 0.0002 #2e-4
batch_size: 10000
value_epochs: 200

# ==== Optimization parameters ====
discount_factor: 0.99
num_conjugate: 10
max_decay_num: 10
line_decay: 0.8
damping_coeff: 0.01
gae_coeff: 0.97

# ==== Training parameters ====
max_ep_len: 1000
max_steps: 4000
epochs: 500
save_freq: 2

# ==== Bounds ====
max_kl: 0.001
cost_d1: 0.0
cost_d2: 0.025

# ==== Testing parameters ====
test_episodes: 10
